Resolve libthrift conflict
- jaeger-thrift which is dependency of jaeger-client requires 0.12.0
  of org.apache.thrift:libthrift
- cassandra-all has 0.9.2 of libthrift as dependency which takes
  precedence over above dependency
- This results in NoSuchMethodError for sendBaseOneway
- This commit excludes org.apache.thrift:libthrift from
  org.apache.cassandra:cassandra-all so that correct version gets
  pulled automatically
- Thanks to @samkulkarni20 for helping out with this issue

Signed-off-by: Bhavin Gandhi <bhavin7392@gmail.com>